# Generated by Django 4.2.2 on 2023-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField()),
                ('book_id', models.CharField(max_length=255, unique=True)),
                ('language', models.CharField(choices=[('English', 'ENGLISH'), ('Spanish', 'SPANISH'), ('Portuguese', 'PORTUGUESE')], max_length=50)),
            ],
        ),
    ]
